services:
  - type: web
    name: zoozoo-farm
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails assets:precompile
      bundle exec rails db:migrate
      bundle exec rails db:seed
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false
